#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <my_app_icons.h>

int32_t my_app_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm my_app!");

    return 0;
}
